# Copyright (C) strawberryhacker

obj-y += /kernel/thread.o
obj-y += /kernel/sched.o
obj-y += /kernel/rt.o
obj-y += /kernel/fair.o
obj-y += /kernel/back.o
obj-y += /kernel/idle.o
obj-y += /kernel/syscall.o
obj-y += /kernel/process.o
obj-y += /kernel/elf.o
obj-y += /kernel/task_manager.o
obj-y += /kernel/pid.o
obj-y += /kernel/atomic.o
obj-y += /kernel/asid.o
