# Copyright (C) strawberryhacker

obj-y += /drivers/apic.o
obj-y += /drivers/matrix.o
obj-y += /drivers/random.o
obj-y += /drivers/pit.o
obj-y += /drivers/timer.o
obj-y += /drivers/clock.o
obj-y += /drivers/gpio.o
obj-y += /drivers/cpu_timer.o
obj-y += /drivers/mmc.o
obj-y += /drivers/sd.o
obj-y += /drivers/dma.o
obj-y += /drivers/spi.o
obj-y += /drivers/lcd.o
obj-y += /drivers/gmac.o
