# Copyright (C) strawberryhacker

linker-script-y += $(TOP)/arch/ddr.ld

obj-y += /arch/entry.o
obj-y += /arch/irq.o
obj-y += /arch/cache.o
obj-y += /arch/fault.o
obj-y += /arch/sched.o
obj-y += /arch/fpu.o
